const createPetModule = require('./createPet');
const deletePetModule = require('./deletePet');
const modifyPetModule = require('./modifyPet');
const checkUserModule = require('./checkUser');
const getListModule = require('./getList');
const getPetIDModule = require('./getPetID');
const createTaskModule = require('./createTask');
const modifyTaskDescriptionModule = require('./modifyTaskDescription');
const deleteTaskModule = require('./deleteTask');
const modifyTaskStatusModule = require('./modifyTaskStatus');

exports.createPet = createPetModule.createPet;
exports.deletePet = deletePetModule.deletePet;
exports.modifyPet = modifyPetModule.modifyPet;
exports.checkUser = checkUserModule.checkUser;
exports.getList = getListModule.getList;
exports.getPetID = getPetIDModule.getPetID
exports.createTask = createTaskModule.createTask;
exports.modifyTaskDescription = modifyTaskDescriptionModule.modifyTaskDescription;
exports.deleteTask = deleteTaskModule.deleteTask;
exports.modifyTaskStatus = modifyTaskStatusModule.modifyTaskStatus;